title: In Lieu of Fun
email: "" # TODO: something better, info@ maybe?
description: >-
  "And...we're live!" A webcast hosted by Ben Wittes and Kate Klonick.
baseurl: ""
url: "https://inlieuof.fun"
twitter_username: inlieuoffunshow
github_username:  inlieuoffun
theme: minima
stream_redirect: false
plugins:
  - jekyll-feed # for Atom syndication
exclude:
  - notes
  - tools
  - README.md
