# Build the site from master with Jekyll, and push the resulting content to the
# branch used for serving.

name: Build and publish ILoF

on:
  push:
    branches:
      - source

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.3
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
